name: dartboy
description: Multiplatform Gameboy Color emulator using dart and flutter.
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^6.4.0
  file_picker: ^10.1.2
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
